#appveyor.yml reference: http://www.appveyor.com/docs/appveyor-yml
version: 0.21.2.{build}
os: Visual Studio 2015 RC
platform: Any CPU
clone_folder: c:\gittfs
clone_depth: 1
# build cache to preserve files/folders between builds
cache:
  - packages -> **\repositories.config  # preserve "packages" directory in the root of build folder but will reset it if repositories.config is modified
init: []
install:
#- choco install tfs2010objectmodel -y
#- choco install tfs2012objectmodel -y
#- choco install tfs2013objectmodel -y
build_script:
  - msbuild GitTfs.sln /t:GitTfs_Vs2015 /verbosity:minimal /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
  - ps: |
      $libgit2Binaries=Get-ChildItem ".\packages\" -Filter "NativeBinaries" -Recurse | Select-Object -First 1 | % { $_.FullName }
      Copy-Item $libgit2Binaries ".\GitTfs.Vs2015\bin\Release\NativeBinaries" -Recurse

test:
  assemblies: '**\GitTfsTest.dll'
after_test:
  - ps: |
      & ".\FunctionalTesting\smoke_tests.ps1" "$Env:APPVEYOR_BUILD_FOLDER\GitTfs.Vs2015\bin\Release"